# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/olivier/C++Unmix/IHMUnmix/fensynthpixel.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FenSynthPixel(object):
    def setupUi(self, FenSynthPixel):
        FenSynthPixel.setObjectName("FenSynthPixel")
        FenSynthPixel.resize(677, 530)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FenSynthPixel)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(FenSynthPixel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.ButtonBrowseLib = QtWidgets.QPushButton(FenSynthPixel)
        self.ButtonBrowseLib.setObjectName("ButtonBrowseLib")
        self.gridLayout.addWidget(self.ButtonBrowseLib, 2, 2, 2, 1)
        self.lineEditLib = QtWidgets.QLineEdit(FenSynthPixel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditLib.sizePolicy().hasHeightForWidth())
        self.lineEditLib.setSizePolicy(sizePolicy)
        self.lineEditLib.setObjectName("lineEditLib")
        self.gridLayout.addWidget(self.lineEditLib, 2, 1, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.LayoutNumbEndmember = QtWidgets.QVBoxLayout()
        self.LayoutNumbEndmember.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.LayoutNumbEndmember.setObjectName("LayoutNumbEndmember")
        self.label_2 = QtWidgets.QLabel(FenSynthPixel)
        self.label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.LayoutNumbEndmember.addWidget(self.label_2)
        self.radioButtR2 = QtWidgets.QRadioButton(FenSynthPixel)
        self.radioButtR2.setChecked(True)
        self.radioButtR2.setObjectName("radioButtR2")
        self.RadioButtonGroup = QtWidgets.QButtonGroup(FenSynthPixel)
        self.RadioButtonGroup.setObjectName("RadioButtonGroup")
        self.RadioButtonGroup.addButton(self.radioButtR2)
        self.LayoutNumbEndmember.addWidget(self.radioButtR2)
        self.radioButtR3 = QtWidgets.QRadioButton(FenSynthPixel)
        self.radioButtR3.setObjectName("radioButtR3")
        self.RadioButtonGroup.addButton(self.radioButtR3)
        self.LayoutNumbEndmember.addWidget(self.radioButtR3)
        self.radioButtR4 = QtWidgets.QRadioButton(FenSynthPixel)
        self.radioButtR4.setObjectName("radioButtR4")
        self.RadioButtonGroup.addButton(self.radioButtR4)
        self.LayoutNumbEndmember.addWidget(self.radioButtR4)
        self.radioButtR5 = QtWidgets.QRadioButton(FenSynthPixel)
        self.radioButtR5.setObjectName("radioButtR5")
        self.RadioButtonGroup.addButton(self.radioButtR5)
        self.LayoutNumbEndmember.addWidget(self.radioButtR5)
        self.radioButtR6 = QtWidgets.QRadioButton(FenSynthPixel)
        self.radioButtR6.setObjectName("radioButtR6")
        self.RadioButtonGroup.addButton(self.radioButtR6)
        self.LayoutNumbEndmember.addWidget(self.radioButtR6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(FenSynthPixel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.a_1Label = QtWidgets.QLabel(FenSynthPixel)
        self.a_1Label.setObjectName("a_1Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.a_1Label)
        self.a_1DoubleSpinBox = QtWidgets.QDoubleSpinBox(FenSynthPixel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a_1DoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.a_1DoubleSpinBox.setSizePolicy(sizePolicy)
        self.a_1DoubleSpinBox.setObjectName("a_1DoubleSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.a_1DoubleSpinBox)
        self.a_2Label = QtWidgets.QLabel(FenSynthPixel)
        self.a_2Label.setObjectName("a_2Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.a_2Label)
        self.a_2DoubleSpinBox = QtWidgets.QDoubleSpinBox(FenSynthPixel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a_2DoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.a_2DoubleSpinBox.setSizePolicy(sizePolicy)
        self.a_2DoubleSpinBox.setObjectName("a_2DoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.a_2DoubleSpinBox)
        self.a_3Label = QtWidgets.QLabel(FenSynthPixel)
        self.a_3Label.setObjectName("a_3Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.a_3Label)
        self.a_3DoubleSpinBox = QtWidgets.QDoubleSpinBox(FenSynthPixel)
        self.a_3DoubleSpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a_3DoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.a_3DoubleSpinBox.setSizePolicy(sizePolicy)
        self.a_3DoubleSpinBox.setObjectName("a_3DoubleSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.a_3DoubleSpinBox)
        self.a_4Label = QtWidgets.QLabel(FenSynthPixel)
        self.a_4Label.setObjectName("a_4Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.a_4Label)
        self.a_4DoubleSpinBox = QtWidgets.QDoubleSpinBox(FenSynthPixel)
        self.a_4DoubleSpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a_4DoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.a_4DoubleSpinBox.setSizePolicy(sizePolicy)
        self.a_4DoubleSpinBox.setObjectName("a_4DoubleSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.a_4DoubleSpinBox)
        self.a_5Label = QtWidgets.QLabel(FenSynthPixel)
        self.a_5Label.setObjectName("a_5Label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.a_5Label)
        self.a_5DoubleSpinBox = QtWidgets.QDoubleSpinBox(FenSynthPixel)
        self.a_5DoubleSpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a_5DoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.a_5DoubleSpinBox.setSizePolicy(sizePolicy)
        self.a_5DoubleSpinBox.setObjectName("a_5DoubleSpinBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.a_5DoubleSpinBox)
        self.a_6Label = QtWidgets.QLabel(FenSynthPixel)
        self.a_6Label.setObjectName("a_6Label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.a_6Label)
        self.a_6DoubleSpinBox = QtWidgets.QDoubleSpinBox(FenSynthPixel)
        self.a_6DoubleSpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a_6DoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.a_6DoubleSpinBox.setSizePolicy(sizePolicy)
        self.a_6DoubleSpinBox.setObjectName("a_6DoubleSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.a_6DoubleSpinBox)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.iterationsLabel = QtWidgets.QLabel(FenSynthPixel)
        self.iterationsLabel.setObjectName("iterationsLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.iterationsLabel)
        self.iterationsSpinBox = QtWidgets.QSpinBox(FenSynthPixel)
        self.iterationsSpinBox.setMinimum(100)
        self.iterationsSpinBox.setMaximum(32768)
        self.iterationsSpinBox.setObjectName("iterationsSpinBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.iterationsSpinBox)
        self.burnInLabel = QtWidgets.QLabel(FenSynthPixel)
        self.burnInLabel.setObjectName("burnInLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.burnInLabel)
        self.burnInSpinBox = QtWidgets.QSpinBox(FenSynthPixel)
        self.burnInSpinBox.setMaximum(32768)
        self.burnInSpinBox.setObjectName("burnInSpinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.burnInSpinBox)
        self.noiseVarianceLabel = QtWidgets.QLabel(FenSynthPixel)
        self.noiseVarianceLabel.setObjectName("noiseVarianceLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.noiseVarianceLabel)
        self.noiseVarianceDoubleSpinBox = QtWidgets.QDoubleSpinBox(FenSynthPixel)
        self.noiseVarianceDoubleSpinBox.setDecimals(4)
        self.noiseVarianceDoubleSpinBox.setMaximum(99.9999)
        self.noiseVarianceDoubleSpinBox.setSingleStep(0.0001)
        self.noiseVarianceDoubleSpinBox.setProperty("value", 0.001)
        self.noiseVarianceDoubleSpinBox.setObjectName("noiseVarianceDoubleSpinBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.noiseVarianceDoubleSpinBox)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.LabelRole, self.formLayout_2)
        self.ButtonUnmix = QtWidgets.QPushButton(FenSynthPixel)
        self.ButtonUnmix.setObjectName("ButtonUnmix")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.ButtonUnmix)
        self.ButtonGenerate = QtWidgets.QPushButton(FenSynthPixel)
        self.ButtonGenerate.setObjectName("ButtonGenerate")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.ButtonGenerate)
        self.verticalLayout.addLayout(self.formLayout)
        self.LayoutNumbEndmember.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.LayoutNumbEndmember)

        self.retranslateUi(FenSynthPixel)
        QtCore.QMetaObject.connectSlotsByName(FenSynthPixel)

    def retranslateUi(self, FenSynthPixel):
        _translate = QtCore.QCoreApplication.translate
        FenSynthPixel.setWindowTitle(_translate("FenSynthPixel", "Unmix synthetic pixel"))
        self.label.setText(_translate("FenSynthPixel", "Load spectral library file (.npy)"))
        self.ButtonBrowseLib.setText(_translate("FenSynthPixel", "Browse..."))
        self.label_2.setText(_translate("FenSynthPixel", "Number of endmembers (R)"))
        self.radioButtR2.setText(_translate("FenSynthPixel", "R = 2"))
        self.radioButtR3.setText(_translate("FenSynthPixel", "R = 3"))
        self.radioButtR4.setText(_translate("FenSynthPixel", "R = 4"))
        self.radioButtR5.setText(_translate("FenSynthPixel", "R = 5"))
        self.radioButtR6.setText(_translate("FenSynthPixel", "R = 6"))
        self.label_3.setText(_translate("FenSynthPixel", "Abundances"))
        self.a_1Label.setText(_translate("FenSynthPixel", "a_1"))
        self.a_2Label.setText(_translate("FenSynthPixel", "a_2"))
        self.a_3Label.setText(_translate("FenSynthPixel", "a_3"))
        self.a_4Label.setText(_translate("FenSynthPixel", "a_4"))
        self.a_5Label.setText(_translate("FenSynthPixel", "a_5"))
        self.a_6Label.setText(_translate("FenSynthPixel", "a_6"))
        self.iterationsLabel.setText(_translate("FenSynthPixel", "Iterations"))
        self.burnInLabel.setText(_translate("FenSynthPixel", "Burn-in"))
        self.noiseVarianceLabel.setText(_translate("FenSynthPixel", "Noise variance"))
        self.ButtonUnmix.setText(_translate("FenSynthPixel", "Unmix !"))
        self.ButtonGenerate.setText(_translate("FenSynthPixel", "Generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FenSynthPixel = QtWidgets.QDialog()
    ui = Ui_FenSynthPixel()
    ui.setupUi(FenSynthPixel)
    FenSynthPixel.show()
    sys.exit(app.exec_())
